name: Build All Modules and Platforms

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout with Submodules
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: gradle/wrapper-validation-action@v1.1.0

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build Everything
        run: ./gradlew :bukkit:build :fabric:build jar_linux_amd64 jar_linux_arm64 jar_windows_amd64

      - name: Upload Bukkit JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: bukkit
          path: bukkit/build/libs/*.jar

      - name: Upload Fabric JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: fabric
          path: fabric/build/libs/*.jar

      - name: Upload Linux AMD64 JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: jar_linux_amd64
          path: **/build/libs/*linux_amd64*.jar

      - name: Upload Linux ARM64 JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: jar_linux_arm64
          path: **/build/libs/*linux_arm64*.jar

      - name: Upload Windows AMD64 JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: jar_windows_amd64
          path: **/build/libs/*windows_amd64*.jar
